application:
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/ttshop
      username: postgres
      password: password
      hikari:
        auto-commit: true
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 10
        idle-timeout: 10000
        max-lifetime: 1000
server:
  port: 8081
spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false